<?php

namespace App;

use App\Scope\BuyerScope;
use Illuminate\Database\Eloquent\Model;

class Buyer extends User
{

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope(new BuyerScope());
    }

    public function transactions(){
        return $this->hasMany(Transaction::class);
    }
}
